source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RBHUD_Example', :exclusive => true do
  pod "RBHUD", :path => "../"
end

target 'RBHUD_Tests', :exclusive => true do
  pod "RBHUD", :path => "../"

  
end
